version: '3'

services:
  management-mysql:
    image: 'mysql:8'
    container_name: musics-db
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: musics
    volumes:
      - .:/docker-entrypoint-initdb.d
