version: '3'

services:
  gateway-service:
    build: ../music-gateway/docker
    image: 'music/gateway'
    container_name: gateway-service
    ports:
      - 3333:3333
    depends_on:
      - publishing-service
      - management-service
  management-service:
    build: ../music-management/docker
    image: 'music/management'
    container_name: management-service
    depends_on:
      - management-mysql
  management-service2:
    build: ../music-management/docker
    image: 'music/management'
    container_name: management-service2
    depends_on:
      - management-mysql
  management-mysql:
    image: 'mysql:8'
    container_name: management-mysql
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: musics
    volumes:
      - ../music-management/docker/schema:/docker-entrypoint-initdb.d
  publishing-service:
    build: ../music-publishing/docker
    image: 'music/publishing'
    container_name: publishing-service
    depends_on:
      - publishing-mysql
  publishing-mysql:
    image: 'mysql:8'
    container_name: publishing-mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: publishings
    volumes:
      - ../music-publishing/docker/schema:/docker-entrypoint-initdb.d

networks:
  default:
    external:
      name: musics

